// Generated by scripts/gen-exercise-catalog.mjs. Do not edit by hand.
export interface CatalogExercise {
  id: string;
  canonicalName: string;
  aliases: string[];
  category: string;
  movementPattern: string;
  isBarbell: boolean;
}

export const EXERCISE_CATALOG: CatalogExercise[] = [
  {
    "id": "fbe64713-d88c-5c0f-94f5-5e3021c28198",
    "canonicalName": "Back Squat",
    "aliases": [
      "Knäböj",
      "Squat",
      "Böj"
    ],
    "category": "legs",
    "movementPattern": "squat",
    "isBarbell": true
  },
  {
    "id": "03abd81c-38da-5164-b817-0e1e972ce83a",
    "canonicalName": "Front Squat",
    "aliases": [
      "Frontböj"
    ],
    "category": "legs",
    "movementPattern": "squat",
    "isBarbell": true
  },
  {
    "id": "3f52b652-a6bd-5f92-af9c-eff9f1918d57",
    "canonicalName": "Box Squat",
    "aliases": [
      "Boxböj",
      "Lådböj"
    ],
    "category": "legs",
    "movementPattern": "squat",
    "isBarbell": true
  },
  {
    "id": "aa5ed82a-98c5-52f8-892b-fe2d39fd546d",
    "canonicalName": "Safety Bar Squat",
    "aliases": [
      "SSB Squat",
      "SSB-böj"
    ],
    "category": "legs",
    "movementPattern": "squat",
    "isBarbell": true
  },
  {
    "id": "36e329e0-6903-5fe7-88cb-b4a2ec219bb2",
    "canonicalName": "Goblet Squat",
    "aliases": [
      "Gobletböj"
    ],
    "category": "legs",
    "movementPattern": "squat",
    "isBarbell": false
  },
  {
    "id": "8475a8d5-cecc-5000-850a-5eaddbfa3293",
    "canonicalName": "Leg Press",
    "aliases": [
      "Benpress"
    ],
    "category": "legs",
    "movementPattern": "squat",
    "isBarbell": false
  },
  {
    "id": "feaa3c56-7568-57db-a3f0-6576d90fdefe",
    "canonicalName": "Deadlift",
    "aliases": [
      "Marklyft",
      "Conventional Deadlift"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": true
  },
  {
    "id": "d2c844b3-4fa9-582d-a1cc-60c9687210a4",
    "canonicalName": "Sumo Deadlift",
    "aliases": [
      "Sumomarklyft"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": true
  },
  {
    "id": "ff93a888-e951-5b62-9621-744843fa0c0e",
    "canonicalName": "Trap Bar Deadlift",
    "aliases": [
      "Trap Bar",
      "Hex Bar Deadlift",
      "Trap bar-marklyft"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": true
  },
  {
    "id": "94126d32-127b-56b2-a627-ec9a239db8d6",
    "canonicalName": "Romanian Deadlift",
    "aliases": [
      "RDL",
      "Rumänsk marklyft"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": true
  },
  {
    "id": "9dbd89cc-d177-50d2-9e26-b64130260cdc",
    "canonicalName": "Good Morning",
    "aliases": [
      "Good Mornings"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": true
  },
  {
    "id": "aec4e498-8f5f-5db4-81f2-1f40bf7ab799",
    "canonicalName": "Hip Thrust",
    "aliases": [
      "Höftlyft",
      "Barbell Hip Thrust"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": true
  },
  {
    "id": "a9b53106-f31b-5009-a5f3-f1608a2e05cf",
    "canonicalName": "Kettlebell Swing",
    "aliases": [
      "KB Swing",
      "Kettlebellsving"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": false
  },
  {
    "id": "18b4aa8c-16a5-5cf7-b3a6-f3b18760654c",
    "canonicalName": "Back Extension",
    "aliases": [
      "Ryggresning",
      "Hyperextension",
      "45° Back Extension"
    ],
    "category": "back",
    "movementPattern": "hinge",
    "isBarbell": false
  },
  {
    "id": "c145dd7f-70c3-577e-8000-635d478085d0",
    "canonicalName": "Reverse Hyper",
    "aliases": [
      "Reverse Hyperextension"
    ],
    "category": "back",
    "movementPattern": "hinge",
    "isBarbell": false
  },
  {
    "id": "1b5826c6-12c6-596c-889d-2506ea099e1d",
    "canonicalName": "Nordic Hamstring Curl",
    "aliases": [
      "Nordic Curl",
      "Nordics",
      "Nordisk hamstring"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": false
  },
  {
    "id": "2dd6ae10-043b-5fc2-8db3-59acc2c3d7e4",
    "canonicalName": "Leg Curl",
    "aliases": [
      "Lårcurl",
      "Hamstring Curl",
      "Liggande lårcurl"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": false
  },
  {
    "id": "5362f9f6-2fc3-5fd9-8d42-d2581d47605e",
    "canonicalName": "Glute Ham Raise",
    "aliases": [
      "GHR"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": false
  },
  {
    "id": "0107d6ab-ceed-5370-980d-3d5e7866a508",
    "canonicalName": "Leg Extension",
    "aliases": [
      "Benspark"
    ],
    "category": "legs",
    "movementPattern": "squat",
    "isBarbell": false
  },
  {
    "id": "561465b8-e186-538d-b89c-d86f1c020209",
    "canonicalName": "Bulgarian Split Squat",
    "aliases": [
      "BSS",
      "Bulgarisk utfallsböj",
      "Bulgarian Split Squats"
    ],
    "category": "legs",
    "movementPattern": "lunge",
    "isBarbell": false
  },
  {
    "id": "3f39d359-b245-5988-8422-646f22c96010",
    "canonicalName": "Walking Lunge",
    "aliases": [
      "Gående utfall",
      "Utfallssteg",
      "Lunges"
    ],
    "category": "legs",
    "movementPattern": "lunge",
    "isBarbell": false
  },
  {
    "id": "848a1c04-7028-5404-b752-4f0a226577e5",
    "canonicalName": "Reverse Lunge",
    "aliases": [
      "Bakåtutfall"
    ],
    "category": "legs",
    "movementPattern": "lunge",
    "isBarbell": false
  },
  {
    "id": "394290c4-afd7-5530-a5ac-ef06fac446ab",
    "canonicalName": "Step-up",
    "aliases": [
      "Step-ups",
      "Uppkliv",
      "Box Step-up"
    ],
    "category": "legs",
    "movementPattern": "lunge",
    "isBarbell": false
  },
  {
    "id": "6836d632-d25d-5fa0-bc86-92fdc9163eef",
    "canonicalName": "Step-down",
    "aliases": [
      "Step-downs",
      "Nedkliv"
    ],
    "category": "legs",
    "movementPattern": "lunge",
    "isBarbell": false
  },
  {
    "id": "5c9eda83-c886-5f04-a1a0-b04b5617aac7",
    "canonicalName": "Single-Leg RDL",
    "aliases": [
      "Enbens-RDL",
      "SL RDL",
      "Single Leg Romanian Deadlift"
    ],
    "category": "legs",
    "movementPattern": "hinge",
    "isBarbell": false
  },
  {
    "id": "79dac392-5d80-5ebe-ab49-357c98b25e99",
    "canonicalName": "Calf Raise",
    "aliases": [
      "Tåhävningar",
      "Vadpress",
      "Standing Calf Raise"
    ],
    "category": "legs",
    "movementPattern": "other",
    "isBarbell": false
  },
  {
    "id": "19962dd8-4b28-5cb9-b5e1-46faadd7bcf8",
    "canonicalName": "Soleus Raise",
    "aliases": [
      "Sittande tåhävningar",
      "Seated Calf Raise"
    ],
    "category": "legs",
    "movementPattern": "other",
    "isBarbell": false
  },
  {
    "id": "26fdf58c-f895-531c-995a-684712735720",
    "canonicalName": "Tibialis Raise",
    "aliases": [
      "Tib Raise",
      "Tibialislyft"
    ],
    "category": "legs",
    "movementPattern": "other",
    "isBarbell": false
  },
  {
    "id": "d685422f-a968-5a9d-aafb-798ff0bdfb86",
    "canonicalName": "Bench Press",
    "aliases": [
      "Bänkpress",
      "Bänk"
    ],
    "category": "chest",
    "movementPattern": "push",
    "isBarbell": true
  },
  {
    "id": "55b9b79e-541f-521d-bbeb-f21a683e03c3",
    "canonicalName": "Speed Bench",
    "aliases": [
      "Speed Bench Press",
      "Snabb bänkpress",
      "DE Bench"
    ],
    "category": "chest",
    "movementPattern": "push",
    "isBarbell": true
  },
  {
    "id": "f13366ae-22da-565a-bc1a-ceb1c2bf204d",
    "canonicalName": "Close-Grip Bench Press",
    "aliases": [
      "CGBP",
      "Smal bänkpress",
      "Close Grip Bench"
    ],
    "category": "chest",
    "movementPattern": "push",
    "isBarbell": true
  },
  {
    "id": "c925a39e-630e-5764-9f07-205360240e0f",
    "canonicalName": "Floor Press",
    "aliases": [
      "Golvpress"
    ],
    "category": "chest",
    "movementPattern": "push",
    "isBarbell": true
  },
  {
    "id": "6cdc8f4b-7f3e-53ca-bda5-a58f3de986f6",
    "canonicalName": "Incline Bench Press",
    "aliases": [
      "Lutande bänkpress",
      "Incline Bench"
    ],
    "category": "chest",
    "movementPattern": "push",
    "isBarbell": true
  },
  {
    "id": "fc0480a1-ee2a-5cba-852c-7c5c8e45797a",
    "canonicalName": "Dumbbell Bench Press",
    "aliases": [
      "DB Bench",
      "Hantelpress"
    ],
    "category": "chest",
    "movementPattern": "push",
    "isBarbell": false
  },
  {
    "id": "4ea09edf-4cdd-5197-acce-5df1334cd6d9",
    "canonicalName": "Overhead Press",
    "aliases": [
      "OHP",
      "Militärpress",
      "Axelpress",
      "Press"
    ],
    "category": "shoulders",
    "movementPattern": "push",
    "isBarbell": true
  },
  {
    "id": "0ad5e03e-e0cb-519a-a589-1c4839bfe1f4",
    "canonicalName": "Dumbbell Shoulder Press",
    "aliases": [
      "Hantelaxelpress",
      "DB Shoulder Press"
    ],
    "category": "shoulders",
    "movementPattern": "push",
    "isBarbell": false
  },
  {
    "id": "4506cfc3-940c-542a-bdc4-77b5cd9a130d",
    "canonicalName": "Push-up",
    "aliases": [
      "Push-ups",
      "Armhävningar"
    ],
    "category": "chest",
    "movementPattern": "push",
    "isBarbell": false
  },
  {
    "id": "f05ed483-6409-5f71-a142-fe41d530cf7a",
    "canonicalName": "Dips",
    "aliases": [
      "Dip"
    ],
    "category": "chest",
    "movementPattern": "push",
    "isBarbell": false
  },
  {
    "id": "7183260a-feb2-53c0-b425-4fc332952d98",
    "canonicalName": "Triceps Extension",
    "aliases": [
      "Tricepspress",
      "Skull Crusher",
      "Triceps Pushdown"
    ],
    "category": "arms",
    "movementPattern": "push",
    "isBarbell": false
  },
  {
    "id": "1d812624-54f6-5d59-a4c8-cb9a7fde1228",
    "canonicalName": "Lateral Raise",
    "aliases": [
      "Sidolyft"
    ],
    "category": "shoulders",
    "movementPattern": "push",
    "isBarbell": false
  },
  {
    "id": "4f6b0d83-6611-5817-8cd6-eed5bfd0b9cf",
    "canonicalName": "Pull-Ups",
    "aliases": [
      "Pull-up",
      "Chins",
      "Chin-Ups",
      "Chin-up",
      "Räckhäv"
    ],
    "category": "back",
    "movementPattern": "pull",
    "isBarbell": false
  },
  {
    "id": "a99d30ea-6b20-548a-9845-00a804018c84",
    "canonicalName": "Lat Pulldown",
    "aliases": [
      "Latsdrag",
      "Pulldown"
    ],
    "category": "back",
    "movementPattern": "pull",
    "isBarbell": false
  },
  {
    "id": "3da25aec-33eb-5fd1-9603-fe493f45dee9",
    "canonicalName": "Barbell Row",
    "aliases": [
      "Skivstångsrodd",
      "Bent-Over Row",
      "Pendlay Row"
    ],
    "category": "back",
    "movementPattern": "pull",
    "isBarbell": true
  },
  {
    "id": "10fa066b-8e6c-58a2-9edf-a256b966d37f",
    "canonicalName": "Dumbbell Row",
    "aliases": [
      "Hantelrodd",
      "DB Row",
      "One-Arm Row"
    ],
    "category": "back",
    "movementPattern": "pull",
    "isBarbell": false
  },
  {
    "id": "ce9d533b-c745-5980-a3b7-12efc6731c87",
    "canonicalName": "Seated Cable Row",
    "aliases": [
      "Sittande rodd",
      "Cable Row"
    ],
    "category": "back",
    "movementPattern": "pull",
    "isBarbell": false
  },
  {
    "id": "f11c22ae-16b3-5bd0-84e7-ab4da98e6bf7",
    "canonicalName": "Inverted Row",
    "aliases": [
      "Ring Row",
      "Omvänd rodd"
    ],
    "category": "back",
    "movementPattern": "pull",
    "isBarbell": false
  },
  {
    "id": "f7752461-313f-5c73-98b4-4001f9e34875",
    "canonicalName": "Face Pull",
    "aliases": [
      "Face Pulls"
    ],
    "category": "shoulders",
    "movementPattern": "pull",
    "isBarbell": false
  },
  {
    "id": "5616378c-248c-54b7-ad08-88abbf39b808",
    "canonicalName": "Band Pull-Apart",
    "aliases": [
      "Pull-Aparts",
      "Band Pull Apart"
    ],
    "category": "shoulders",
    "movementPattern": "pull",
    "isBarbell": false
  },
  {
    "id": "00eb0da8-562a-5ee3-8b66-fe78f1ffa653",
    "canonicalName": "Biceps Curl",
    "aliases": [
      "Bicepscurl",
      "Curl",
      "Hammer Curl"
    ],
    "category": "arms",
    "movementPattern": "pull",
    "isBarbell": false
  },
  {
    "id": "b6462930-42a6-55b2-ab88-cc6434f8ad85",
    "canonicalName": "Plank",
    "aliases": [
      "Planka"
    ],
    "category": "core",
    "movementPattern": "core",
    "isBarbell": false
  },
  {
    "id": "88885917-43d7-50ed-b367-92ba768a1e05",
    "canonicalName": "Side Plank",
    "aliases": [
      "Sidoplanka"
    ],
    "category": "core",
    "movementPattern": "core",
    "isBarbell": false
  },
  {
    "id": "6c03bd62-7040-5381-866c-829d7239db49",
    "canonicalName": "Copenhagen Plank",
    "aliases": [
      "Copenhagen",
      "Köpenhamnsplanka",
      "Copenhagen Adduction"
    ],
    "category": "core",
    "movementPattern": "core",
    "isBarbell": false
  },
  {
    "id": "43da5cdd-1816-5f77-b624-aad02a35b144",
    "canonicalName": "Dead Bug",
    "aliases": [
      "Dead Bugs"
    ],
    "category": "core",
    "movementPattern": "core",
    "isBarbell": false
  },
  {
    "id": "40132a54-11b6-55e8-8d53-ba00c39a02e9",
    "canonicalName": "Pallof Press",
    "aliases": [
      "Pallofpress"
    ],
    "category": "core",
    "movementPattern": "core",
    "isBarbell": false
  },
  {
    "id": "b5585a07-2d0f-599b-85f8-809d6807fe5e",
    "canonicalName": "Ab Wheel",
    "aliases": [
      "Ab Rollout",
      "Magrulle"
    ],
    "category": "core",
    "movementPattern": "core",
    "isBarbell": false
  },
  {
    "id": "1ffa5925-5b1d-5639-aa25-cc9c611fa573",
    "canonicalName": "Hanging Leg Raise",
    "aliases": [
      "Hängande benlyft",
      "Leg Raise"
    ],
    "category": "core",
    "movementPattern": "core",
    "isBarbell": false
  },
  {
    "id": "38266218-7962-54c1-93b8-141773b5ea39",
    "canonicalName": "Farmer's Carry",
    "aliases": [
      "Farmers Walk",
      "Farmer Carry",
      "Bondgång"
    ],
    "category": "full_body",
    "movementPattern": "carry",
    "isBarbell": false
  },
  {
    "id": "e780428c-4886-57fe-8a4f-7082ff6c1f8f",
    "canonicalName": "Suitcase Carry",
    "aliases": [
      "Resväskebär"
    ],
    "category": "core",
    "movementPattern": "carry",
    "isBarbell": false
  },
  {
    "id": "cd8c746f-2754-5c78-af18-671d893d812a",
    "canonicalName": "Sled Push",
    "aliases": [
      "Släde",
      "Prowler"
    ],
    "category": "full_body",
    "movementPattern": "carry",
    "isBarbell": false
  },
  {
    "id": "3229b50c-ae77-5494-85a5-b1a4275b31b0",
    "canonicalName": "Box Jump",
    "aliases": [
      "Box Jumps",
      "Lådhopp"
    ],
    "category": "legs",
    "movementPattern": "squat",
    "isBarbell": false
  },
  {
    "id": "6d56995e-1898-53fb-abee-468aae6acea8",
    "canonicalName": "Broad Jump",
    "aliases": [
      "Längdhopp utan ansats",
      "Stående längdhopp"
    ],
    "category": "legs",
    "movementPattern": "squat",
    "isBarbell": false
  },
  {
    "id": "bf85ae75-0b61-5b34-9ce0-e05ca1d6e1bc",
    "canonicalName": "Pogo Jumps",
    "aliases": [
      "Pogo",
      "Pogohopp"
    ],
    "category": "legs",
    "movementPattern": "other",
    "isBarbell": false
  },
  {
    "id": "7554a623-cbd1-501e-a9d8-94da42bb53d6",
    "canonicalName": "Mobility",
    "aliases": [
      "Rörlighet",
      "Rörlighetsträning",
      "Stretch",
      "Stretching"
    ],
    "category": "mobility",
    "movementPattern": "mobility",
    "isBarbell": false
  },
  {
    "id": "5e1922d8-65cf-5179-b9e7-587cfd035434",
    "canonicalName": "Hip Airplane",
    "aliases": [
      "Hip Airplanes",
      "Höftflygplan"
    ],
    "category": "mobility",
    "movementPattern": "mobility",
    "isBarbell": false
  },
  {
    "id": "2f34e216-0f13-5ff5-87c8-cb802f69d91a",
    "canonicalName": "Foam Rolling",
    "aliases": [
      "Foam Roller",
      "Rulla"
    ],
    "category": "mobility",
    "movementPattern": "mobility",
    "isBarbell": false
  }
];
